// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LabController from "./lab_controller"
application.register("lab", LabController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)
import VoltageController from "./voltage_controller"
application.register("voltage", VoltageController)
import PipetteController from "./pipette_controller"
application.register("pipette", PipetteController)
import GelController from "./gel_controller"
application.register("gel", GelController)
import GelPrepController from "./gel_prep_controller"
application.register("gel-prep", GelPrepController)
import GelRunController from "./gel_run_controller"
application.register("gel-run", GelRunController)
import LabelMatchController from "./label_match_controller"
application.register("label-match", LabelMatchController)

import UvExamController from "./uv_exam_controller"
application.register("uv-exam", UvExamController)

import ConclusionTableController from "./conclusion_table_controller"
application.register("conclusion-table", ConclusionTableController)

import AssignmentFormController from "./assignment_form_controller"
application.register("assignment-form", AssignmentFormController)

import StudentQuizController from "./student_quiz_controller"
application.register("student-quiz", StudentQuizController)
