// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LabController from "./lab_controller"
application.register("lab", LabController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)
import VoltageController from "./voltage_controller"
application.register("voltage", VoltageController)
import PipetteController from "./pipette_controller"
application.register("pipette", PipetteController)
